
version: 2.1
jobs:
  build:
    docker:
    macos:
      xcode: 13.4.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "54:c1:34:15:1d:4b:24:30:92:68:27:69:fe:5e:38:3d"

      - run:
          name: push_GitHub
          command: |


          echo 1 > STAR
          echo 2 > STARlong

          ls -l
          #./STAR --version
          #./STARlong --version
          git add STAR STARlong
          git commit -a -m "Added STAR STARlong"
          git push origin master
