os: osx

git:
  submodules: false

before_script:
   - chmod +x .travis.install
   - ./.travis.install
   - git clone --depth 1 https://github.com/alexdobin/STAR STARcompile

script:
   - cd STARcompile/source
   - gpp=`find /usr/local/Cellar/ -name 'g++-*'`
   - echo $gpp
   - make STARforMacStatic CXX=$gpp
   - ./STAR
   - cp STAR ../..
   - make clean
   - make STARlongForMacStatic CXX=$gpp
   - ./STARlong
   - cp STARlong ../..

after_success:
  - cd ../..
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  
  - git clone git@github.com:alexdobin/travis-tests1
  - cd travis-tests1
  - git config user.name alexdobin
  - git config user.email dobin@cshl.edu
  - cp ../STAR ../STARlong ./
  - ls -l
  - ./STAR --version
  - ./STARlong --version
  - git add STAR STARlong
  - git commit -a -m "Added STAR STARlong"
  - git push origin master
