
version: 2.1
jobs:
  build:
    docker:
    macos:
      xcode: 13.4.1
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
