jobs:
  build:
    macos:
      xcode: 13.4.1
          steps:
              - run: brew install gcc
              - run: brew info gcc
              - run: git clone --depth 1 https://github.com/alexdobin/STAR STARcompile

              - run: cd STARcompile/source
              - run: gpp=`find /usr/local/Cellar/ -name 'g++-*'`
              - run: echo $gpp
              - run: make STARforMacStatic CXX=$gpp
              - run: ./STAR
              - run: cp STAR ../..
              - run: make clean
              - run: make STARlongForMacStatic CXX=$gpp
              - run: ./STARlong
              - run: cp STARlong ../..

              - run: cd ../..
              - run: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
              - run: eval "$(ssh-agent -s)" #start the ssh agent
              - run: chmod 600 .travis/deploy_key.pem # this key should have push access
              - run: ssh-add .travis/deploy_key.pem

              - run: git clone git@github.com:alexdobin/travis-tests1
              - run: cd travis-tests1
              - run: git config user.name alexdobin
              - run: git config user.email dobin@cshl.edu
              - run: cp ../STAR ../STARlong ./
              - run: ls -l
              - run: ./STAR --version
              - run: ./STARlong --version
              - run: git add STAR STARlong
              - run: git commit -a -m "Added STAR STARlong"
              - run: git push origin master
