
version: 2.1
jobs:
  build:
    docker:
    macos:
      xcode: 13.4.1
    steps:
      - run:
          name: GCC
          command: |
            brew install gcc
            brew info gcc


      - run:
          name: compile_STAR
          command: |
            gpp=`find /usr/local/Cellar/ -name 'g++-12'`
            echo $gpp
            git clone --depth 1 https://github.com/alexdobin/STAR STARcompile
            cd STARcompile/source
            make STARforMacStatic CXX=$gpp
            ./STAR
            cp STAR ../..
            make clean
            make STARlongForMacStatic CXX=$gpp
            ./STARlong
            cp STARlong ../..
